[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "learning_vllm"
version = "0.1.0"
authors = [{ name = "ellen", email = "ellenlee8182@gmail.com" }]
readme = "README.md"
requires-python = ">=3.10, <3.13"
dynamic = ["dependencies"]